export const timezones = [
  // Africa
  { value: 'Africa/Abidjan', label: 'Abidjan (GMT+0)' },
  { value: 'Africa/Accra', label: 'Accra (GMT+0)' },
  { value: 'Africa/Addis_Ababa', label: 'Addis Ababa (GMT+3)' },
  { value: 'Africa/Algiers', label: 'Algiers (GMT+1)' },
  { value: 'Africa/Asmara', label: 'Asmara (GMT+3)' },
  { value: 'Africa/Bamako', label: 'Bamako (GMT+0)' },
  { value: 'Africa/Bangui', label: 'Bangui (GMT+1)' },
  { value: 'Africa/Banjul', label: 'Banjul (GMT+0)' },
  { value: 'Africa/Bissau', label: 'Bissau (GMT+0)' },
  { value: 'Africa/Blantyre', label: 'Blantyre (GMT+2)' },
  { value: 'Africa/Brazzaville', label: 'Brazzaville (GMT+1)' },
  { value: 'Africa/Bujumbura', label: 'Bujumbura (GMT+2)' },
  { value: 'Africa/Cairo', label: 'Cairo (GMT+2)' },
  { value: 'Africa/Casablanca', label: 'Casablanca (GMT+1)' },
  { value: 'Africa/Ceuta', label: 'Ceuta (GMT+1/+2)' },
  { value: 'Africa/Conakry', label: 'Conakry (GMT+0)' },
  { value: 'Africa/Dakar', label: 'Dakar (GMT+0)' },
  { value: 'Africa/Dar_es_Salaam', label: 'Dar es Salaam (GMT+3)' },
  { value: 'Africa/Djibouti', label: 'Djibouti (GMT+3)' },
  { value: 'Africa/Douala', label: 'Douala (GMT+1)' },
  { value: 'Africa/El_Aaiun', label: 'El Aaiun (GMT+0/+1)' },
  { value: 'Africa/Freetown', label: 'Freetown (GMT+0)' },
  { value: 'Africa/Gaborone', label: 'Gaborone (GMT+2)' },
  { value: 'Africa/Harare', label: 'Harare (GMT+2)' },
  { value: 'Africa/Johannesburg', label: 'Johannesburg (GMT+2)' },
  { value: 'Africa/Juba', label: 'Juba (GMT+3)' },
  { value: 'Africa/Kampala', label: 'Kampala (GMT+3)' },
  { value: 'Africa/Khartoum', label: 'Khartoum (GMT+2)' },
  { value: 'Africa/Kigali', label: 'Kigali (GMT+2)' },
  { value: 'Africa/Kinshasa', label: 'Kinshasa (GMT+1)' },
  { value: 'Africa/Lagos', label: 'Lagos (GMT+1)' },
  { value: 'Africa/Libreville', label: 'Libreville (GMT+1)' },
  { value: 'Africa/Lome', label: 'Lomé (GMT+0)' },
  { value: 'Africa/Luanda', label: 'Luanda (GMT+1)' },
  { value: 'Africa/Lubumbashi', label: 'Lubumbashi (GMT+2)' },
  { value: 'Africa/Lusaka', label: 'Lusaka (GMT+2)' },
  { value: 'Africa/Malabo', label: 'Malabo (GMT+1)' },
  { value: 'Africa/Maputo', label: 'Maputo (GMT+2)' },
  { value: 'Africa/Maseru', label: 'Maseru (GMT+2)' },
  { value: 'Africa/Mbabane', label: 'Mbabane (GMT+2)' },
  { value: 'Africa/Mogadishu', label: 'Mogadishu (GMT+3)' },
  { value: 'Africa/Monrovia', label: 'Monrovia (GMT+0)' },
  { value: 'Africa/Nairobi', label: 'Nairobi (GMT+3)' },
  { value: 'Africa/Ndjamena', label: 'Ndjamena (GMT+1)' },
  { value: 'Africa/Niamey', label: 'Niamey (GMT+1)' },
  { value: 'Africa/Nouakchott', label: 'Nouakchott (GMT+0)' },
  { value: 'Africa/Ouagadougou', label: 'Ouagadougou (GMT+0)' },
  { value: 'Africa/Porto-Novo', label: 'Porto-Novo (GMT+1)' },
  { value: 'Africa/Sao_Tome', label: 'São Tomé (GMT+0)' },
  { value: 'Africa/Tripoli', label: 'Tripoli (GMT+2)' },
  { value: 'Africa/Tunis', label: 'Tunis (GMT+1)' },
  { value: 'Africa/Windhoek', label: 'Windhoek (GMT+2)' },

  // Americas
  { value: 'America/Anchorage', label: 'Anchorage (GMT-9/-8)' },
  { value: 'America/Antigua', label: 'Antigua (GMT-4)' },
  { value: 'America/Araguaina', label: 'Araguaina (GMT-3)' },
  { value: 'America/Argentina/Buenos_Aires', label: 'Buenos Aires (GMT-3)' },
  { value: 'America/Asuncion', label: 'Asunción (GMT-4/-3)' },
  { value: 'America/Barbados', label: 'Barbados (GMT-4)' },
  { value: 'America/Belem', label: 'Belém (GMT-3)' },
  { value: 'America/Belize', label: 'Belize (GMT-6)' },
  { value: 'America/Boa_Vista', label: 'Boa Vista (GMT-4)' },
  { value: 'America/Bogota', label: 'Bogota (GMT-5)' },
  { value: 'America/Caracas', label: 'Caracas (GMT-4)' },
  { value: 'America/Cayenne', label: 'Cayenne (GMT-3)' },
  { value: 'America/Cayman', label: 'Cayman Islands (GMT-5)' },
  { value: 'America/Chicago', label: 'Chicago (GMT-6/-5)' },
  { value: 'America/Cuiaba', label: 'Cuiabá (GMT-4/-3)' },
  { value: 'America/Denver', label: 'Denver (GMT-7/-6)' },
  { value: 'America/Dominica', label: 'Dominica (GMT-4)' },
  { value: 'America/Edmonton', label: 'Edmonton (GMT-7/-6)' },
  { value: 'America/El_Salvador', label: 'El Salvador (GMT-6)' },
  { value: 'America/Fortaleza', label: 'Fortaleza (GMT-3)' },
  { value: 'America/Glace_Bay', label: 'Glace Bay (GMT-4/-3)' },
  { value: 'America/Godthab', label: 'Godthåb (GMT-3/-2)' },
  { value: 'America/Goose_Bay', label: 'Goose Bay (GMT-4/-3)' },
  { value: 'America/Grand_Turk', label: 'Grand Turk (GMT-5/-4)' },
  { value: 'America/Grenada', label: 'Grenada (GMT-4)' },
  { value: 'America/Guadeloupe', label: 'Guadeloupe (GMT-4)' },
  { value: 'America/Guatemala', label: 'Guatemala (GMT-6)' },
  { value: 'America/Guayaquil', label: 'Guayaquil (GMT-5)' },
  { value: 'America/Guyana', label: 'Guyana (GMT-4)' },
  { value: 'America/Halifax', label: 'Halifax (GMT-4/-3)' },
  { value: 'America/Havana', label: 'Havana (GMT-5/-4)' },
  { value: 'America/Hermosillo', label: 'Hermosillo (GMT-7)' },
  { value: 'America/Indiana/Indianapolis', label: 'Indianapolis (GMT-5/-4)' },
  { value: 'America/Jamaica', label: 'Jamaica (GMT-5)' },
  { value: 'America/Juneau', label: 'Juneau (GMT-9/-8)' },
  { value: 'America/La_Paz', label: 'La Paz (GMT-4)' },
  { value: 'America/Lima', label: 'Lima (GMT-5)' },
  { value: 'America/Los_Angeles', label: 'Los Angeles (GMT-8/-7)' },
  { value: 'America/Maceio', label: 'Maceió (GMT-3)' },
  { value: 'America/Managua', label: 'Managua (GMT-6)' },
  { value: 'America/Manaus', label: 'Manaus (GMT-4)' },
  { value: 'America/Martinique', label: 'Martinique (GMT-4)' },
  { value: 'America/Mazatlan', label: 'Mazatlán (GMT-7/-6)' },
  { value: 'America/Mexico_City', label: 'Mexico City (GMT-6/-5)' },
  { value: 'America/Miquelon', label: 'Miquelon (GMT-3/-2)' },
  { value: 'America/Montevideo', label: 'Montevideo (GMT-3)' },
  { value: 'America/Montreal', label: 'Montreal (GMT-5/-4)' },
  { value: 'America/Nassau', label: 'Nassau (GMT-5/-4)' },
  { value: 'America/New_York', label: 'New York (GMT-5/-4)' },
  { value: 'America/Nipigon', label: 'Nipigon (GMT-5/-4)' },
  { value: 'America/Panama', label: 'Panama (GMT-5)' },
  { value: 'America/Paramaribo', label: 'Paramaribo (GMT-3)' },
  { value: 'America/Phoenix', label: 'Phoenix (GMT-7)' },
  { value: 'America/Port-au-Prince', label: 'Port-au-Prince (GMT-5)' },
  { value: 'America/Port_of_Spain', label: 'Port of Spain (GMT-4)' },
  { value: 'America/Porto_Velho', label: 'Porto Velho (GMT-4)' },
  { value: 'America/Puerto_Rico', label: 'Puerto Rico (GMT-4)' },
  { value: 'America/Rainy_River', label: 'Rainy River (GMT-6/-5)' },
  { value: 'America/Recife', label: 'Recife (GMT-3)' },
  { value: 'America/Regina', label: 'Regina (GMT-6)' },
  { value: 'America/Resolute', label: 'Resolute (GMT-6/-5)' },
  { value: 'America/Rio_Branco', label: 'Rio Branco (GMT-5)' },
  { value: 'America/Sao_Paulo', label: 'São Paulo (GMT-3)' },
  { value: 'America/Santarem', label: 'Santarém (GMT-3)' },
  { value: 'America/Santo_Domingo', label: 'Santo Domingo (GMT-4)' },
  { value: 'America/St_Johns', label: "St. John's (GMT-4/-3)" },
  { value: 'America/St_Kitts', label: 'St. Kitts (GMT-4)' },
  { value: 'America/St_Lucia', label: 'St. Lucia (GMT-4)' },
  { value: 'America/St_Vincent', label: 'St. Vincent (GMT-4)' },
  { value: 'America/Swift_Current', label: 'Swift Current (GMT-6)' },
  { value: 'America/Tegucigalpa', label: 'Tegucigalpa (GMT-6)' },
  { value: 'America/Thunder_Bay', label: 'Thunder Bay (GMT-5/-4)' },
  { value: 'America/Toronto', label: 'Toronto (GMT-5/-4)' },
  { value: 'America/Tortola', label: 'Tortola (GMT-4)' },
  { value: 'America/Vancouver', label: 'Vancouver (GMT-8/-7)' },
  { value: 'America/Whitehorse', label: 'Whitehorse (GMT-8/-7)' },
  { value: 'America/Winnipeg', label: 'Winnipeg (GMT-6/-5)' },
  { value: 'America/Yakutat', label: 'Yakutat (GMT-9/-8)' },
  // Europe
  { value: 'Europe/Amsterdam', label: 'Amsterdam (GMT+1/+2)' },
  { value: 'Europe/Andorra', label: 'Andorra (GMT+1/+2)' },
  { value: 'Europe/Athens', label: 'Athens (GMT+2/+3)' },
  { value: 'Europe/Belgrade', label: 'Belgrade (GMT+1/+2)' },
  { value: 'Europe/Berlin', label: 'Berlin (GMT+1/+2)' },
  { value: 'Europe/Bratislava', label: 'Bratislava (GMT+1/+2)' },
  { value: 'Europe/Brussels', label: 'Brussels (GMT+1/+2)' },
  { value: 'Europe/Bucharest', label: 'Bucharest (GMT+2/+3)' },
  { value: 'Europe/Budapest', label: 'Budapest (GMT+1/+2)' },
  { value: 'Europe/Chisinau', label: 'Chișinău (GMT+2/+3)' },
  { value: 'Europe/Copenhagen', label: 'Copenhagen (GMT+1/+2)' },
  { value: 'Europe/Dublin', label: 'Dublin (GMT+0/+1)' },
  { value: 'Europe/Helsinki', label: 'Helsinki (GMT+2/+3)' },
  { value: 'Europe/Istanbul', label: 'Istanbul (GMT+3)' },
  { value: 'Europe/Kaliningrad', label: 'Kaliningrad (GMT+2)' },
  { value: 'Europe/Kiev', label: 'Kyiv (GMT+2/+3)' },
  { value: 'Europe/Lisbon', label: 'Lisbon (GMT+0/+1)' },
  { value: 'Europe/Ljubljana', label: 'Ljubljana (GMT+1/+2)' },
  { value: 'Europe/London', label: 'London (GMT+0/+1)' },
  { value: 'Europe/Luxembourg', label: 'Luxembourg (GMT+1/+2)' },
  { value: 'Europe/Madrid', label: 'Madrid (GMT+1/+2)' },
  { value: 'Europe/Malta', label: 'Malta (GMT+1/+2)' },
  { value: 'Europe/Minsk', label: 'Minsk (GMT+3)' },
  { value: 'Europe/Monaco', label: 'Monaco (GMT+1/+2)' },
  { value: 'Europe/Moscow', label: 'Moscow (GMT+3)' },
  { value: 'Europe/Oslo', label: 'Oslo (GMT+1/+2)' },
  { value: 'Europe/Paris', label: 'Paris (GMT+1/+2)' },
  { value: 'Europe/Podgorica', label: 'Podgorica (GMT+1/+2)' },
  { value: 'Europe/Prague', label: 'Prague (GMT+1/+2)' },
  { value: 'Europe/Riga', label: 'Riga (GMT+2/+3)' },
  { value: 'Europe/Rome', label: 'Rome (GMT+1/+2)' },
  { value: 'Europe/Samara', label: 'Samara (GMT+4)' },
  { value: 'Europe/San_Marino', label: 'San Marino (GMT+1/+2)' },
  { value: 'Europe/Sarajevo', label: 'Sarajevo (GMT+1/+2)' },
  { value: 'Europe/Simferopol', label: 'Simferopol (GMT+3)' },
  { value: 'Europe/Skopje', label: 'Skopje (GMT+1/+2)' },
  { value: 'Europe/Sofia', label: 'Sofia (GMT+2/+3)' },
  { value: 'Europe/Stockholm', label: 'Stockholm (GMT+1/+2)' },
  { value: 'Europe/Tallinn', label: 'Tallinn (GMT+2/+3)' },
  { value: 'Europe/Tirane', label: 'Tirana (GMT+1/+2)' },
  { value: 'Europe/Uzhgorod', label: 'Uzhhorod (GMT+2/+3)' },
  { value: 'Europe/Vaduz', label: 'Vaduz (GMT+1/+2)' },
  { value: 'Europe/Vatican', label: 'Vatican (GMT+1/+2)' },
];
