export const colorPalettes = [
  {
    name: 'Big Deep Forest',
    colors: [
      {
        name: 'Primary',
        colorName: 'green',
        hex: '#1B4332',
        class: 'bg-emerald-900', // Equivalent Tailwind
        hoverClass: 'hover:bg-emerald-900',
        focusClass: 'ring-red-500',
        borderClass: 'border-green-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-green-600',
        textPrimary: 'text-green-900',
        textDark: 'text-green-100',
        textOpacity: 'bg-green-50',
        textDarkOpacity: 'bg-green-900/30',
      },
      {
        name: 'Secondary',
        colorName: 'lime',
        hex: '#486B00',
        class: 'bg-lime-800', // Equivalent Tailwind
        hoverClass: 'hover:bg-lime-800',
        focusClass: 'ring-lime-800/50',
        borderClass: 'border-lime-800',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-lime-800',
        textPrimary: 'text-lime-800',
        textDark: 'text-lime-100',
        textOpacity: 'bg-lime-50',
        textDarkOpacity: 'bg-lime-800/30',
      },
      {
        name: 'Accent',
        colorName: 'lime-light',
        hex: '#A2C523',
        class: 'bg-lime-400', // Equivalent Tailwind
        hoverClass: 'hover:bg-lime-400',
        focusClass: 'ring-lime-400/50',
        borderClass: 'border-lime-400',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-lime-400',
        textPrimary: 'text-lime-400',
        textDark: 'text-lime-50',
        textOpacity: 'bg-lime-50',
        textDarkOpacity: 'bg-lime-400/30',
      },
    ],
  },
  {
    name: 'Sunset Delight',
    colors: [
      {
        name: 'Primary',
        colorName: 'orange',
        hex: '#FF7F50',
        class: 'bg-orange-500', // Equivalent Tailwind
        hoverClass: 'hover:bg-orange-600',
        focusClass: 'ring-orange-500',
        borderClass: 'border-orange-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-orange-600',
        textPrimary: 'text-orange-500',
        textDark: 'text-orange-100',
        textOpacity: 'bg-orange-50',
        textDarkOpacity: 'bg-orange-500/30',
      },
      {
        name: 'Secondary',
        colorName: 'red-orange',
        hex: '#FF4500',
        class: 'bg-orange-700', // Equivalent Tailwind
        hoverClass: 'hover:bg-orange-800',
        focusClass: 'ring-orange-700/50',
        borderClass: 'border-orange-700',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-orange-700',
        textPrimary: 'text-orange-700',
        textDark: 'text-orange-50',
        textOpacity: 'bg-orange-50',
        textDarkOpacity: 'bg-orange-700/30',
      },
      {
        name: 'Accent',
        colorName: 'yellow',
        hex: '#FFD700',
        class: 'bg-yellow-400', // Equivalent Tailwind
        hoverClass: 'hover:bg-yellow-500',
        focusClass: 'ring-yellow-400/50',
        borderClass: 'border-yellow-400',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-yellow-400',
        textPrimary: 'text-yellow-400',
        textDark: 'text-yellow-50',
        textOpacity: 'bg-yellow-50',
        textDarkOpacity: 'bg-yellow-400/30',
      },
    ],
  },
  {
    name: 'Ocean Breeze',
    colors: [
      {
        name: 'Primary',
        colorName: 'blue',
        hex: '#0077B6',
        class: 'bg-sky-600', // Equivalent Tailwind
        hoverClass: 'hover:bg-sky-700',
        focusClass: 'ring-sky-500',
        borderClass: 'border-sky-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-sky-600',
        textPrimary: 'text-sky-600',
        textDark: 'text-sky-100',
        textOpacity: 'bg-sky-50',
        textDarkOpacity: 'bg-sky-600/30',
      },
      {
        name: 'Secondary',
        colorName: 'light-blue',
        hex: '#0096C7',
        class: 'bg-sky-500', // Equivalent Tailwind
        hoverClass: 'hover:bg-sky-600',
        focusClass: 'ring-sky-600/50',
        borderClass: 'border-sky-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-sky-500',
        textPrimary: 'text-sky-500',
        textDark: 'text-sky-50',
        textOpacity: 'bg-sky-50',
        textDarkOpacity: 'bg-sky-500/30',
      },
      {
        name: 'Accent',
        colorName: 'cyan',
        hex: '#00B4D8',
        class: 'bg-cyan-400', // Equivalent Tailwind
        hoverClass: 'hover:bg-cyan-500',
        focusClass: 'ring-cyan-400/50',
        borderClass: 'border-cyan-400',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-cyan-400',
        textPrimary: 'text-cyan-400',
        textDark: 'text-cyan-50',
        textOpacity: 'bg-cyan-50',
        textDarkOpacity: 'bg-cyan-400/30',
      },
    ],
  },
];
