export const colorPalettes = [
  {
    name: 'Big Deep Forest',
    colors: [
      {
        name: 'Primary',
        colorName: 'green',
        hex: '#1B4332',
        class: 'bg-emerald-900',
        hoverClass: 'hover:bg-emerald-900',
        focusClass: 'ring-red-500',
        borderClass: 'border-green-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-green-600',
        textPrimary: 'text-green-900',
        textDark: 'text-green-100',
        textOpacity: 'bg-green-50',
        textDarkOpacity: 'bg-green-900/30',
      },
      {
        name: 'Secondary',
        colorName: 'lime',
        hex: '#156D15',
        class: 'bg-lime-800',
        hoverClass: 'hover:bg-lime-800',
        focusClass: 'ring-lime-800/50',
        borderClass: 'border-lime-800',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-lime-800',
        textPrimary: 'text-lime-800',
        textDark: 'text-lime-100',
        textOpacity: 'bg-lime-50',
        textDarkOpacity: 'bg-lime-800/30',
      },
    ],
  },
  {
    name: 'Sunset Delight',
    colors: [
      {
        name: 'Primary',
        colorName: 'orange',
        hex: '#FF7F50',
        class: 'bg-orange-500', // Equivalent Tailwind
        hoverClass: 'hover:bg-orange-600',
        focusClass: 'ring-orange-500',
        borderClass: 'border-orange-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-orange-600',
        textPrimary: 'text-orange-500',
        textDark: 'text-orange-100',
        textOpacity: 'bg-orange-50',
        textDarkOpacity: 'bg-orange-500/30',
      },
      {
        name: 'Secondary',
        colorName: 'red-orange',
        hex: '#5A1900',
        class: 'bg-orange-700', // Equivalent Tailwind
        hoverClass: 'hover:bg-orange-800',
        focusClass: 'ring-orange-700/50',
        borderClass: 'border-orange-700',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-orange-700',
        textPrimary: 'text-orange-700',
        textDark: 'text-orange-50',
        textOpacity: 'bg-orange-50',
        textDarkOpacity: 'bg-orange-700/30',
      },
    ],
  },
  {
    name: 'Ocean Breeze',
    colors: [
      {
        name: 'Primary',
        colorName: 'blue',
        hex: '#0077B6',
        class: 'bg-sky-600', // Equivalent Tailwind
        hoverClass: 'hover:bg-sky-700',
        focusClass: 'ring-sky-500',
        borderClass: 'border-sky-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-sky-600',
        textPrimary: 'text-sky-600',
        textDark: 'text-sky-100',
        textOpacity: 'bg-sky-50',
        textDarkOpacity: 'bg-sky-600/30',
      },
      {
        name: 'Secondary',
        colorName: 'light-blue',
        hex: '#154c79',
        class: 'bg-sky-500', // Equivalent Tailwind
        hoverClass: 'hover:bg-sky-600',
        focusClass: 'ring-sky-600/50',
        borderClass: 'border-sky-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-sky-500',
        textPrimary: 'text-sky-500',
        textDark: 'text-sky-50',
        textOpacity: 'bg-sky-50',
        textDarkOpacity: 'bg-sky-500/30',
      },
    ],
  },
  {
    name: 'Crimson Horizon',
    colors: [
      {
        name: 'Primary',
        colorName: 'crimson',
        hex: '#DC143C',
        class: 'bg-red-700',
        hoverClass: 'hover:bg-red-800',
        focusClass: 'ring-red-600',
        borderClass: 'border-red-600',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-red-700',
        textPrimary: 'text-red-700',
        textDark: 'text-red-50',
        textOpacity: 'bg-red-50',
        textDarkOpacity: 'bg-red-700/30',
      },
      {
        name: 'Secondary',
        colorName: 'soft-pink',
        hex: '#5C0013',
        class: 'bg-pink-500',
        hoverClass: 'hover:bg-pink-600',
        focusClass: 'ring-pink-500/50',
        borderClass: 'border-pink-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-pink-500',
        textPrimary: 'text-pink-500',
        textDark: 'text-pink-50',
        textOpacity: 'bg-pink-50',
        textDarkOpacity: 'bg-pink-500/30',
      },
    ],
  },

  {
    name: 'Royal Indigo',
    colors: [
      {
        name: 'Primary',
        colorName: 'indigo',
        hex: '#3F51B5',
        class: 'bg-indigo-600',
        hoverClass: 'hover:bg-indigo-700',
        focusClass: 'ring-indigo-500',
        borderClass: 'border-indigo-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-indigo-600',
        textPrimary: 'text-indigo-600',
        textDark: 'text-indigo-50',
        textOpacity: 'bg-indigo-50',
        textDarkOpacity: 'bg-indigo-600/30',
      },
      {
        name: 'Secondary',
        colorName: 'violet',
        hex: '#2B0077',
        class: 'bg-violet-600',
        hoverClass: 'hover:bg-violet-700',
        focusClass: 'ring-violet-500/50',
        borderClass: 'border-violet-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-violet-600',
        textPrimary: 'text-violet-600',
        textDark: 'text-violet-50',
        textOpacity: 'bg-violet-50',
        textDarkOpacity: 'bg-violet-600/30',
      },
    ],
  },

  {
    name: 'Lavender Bliss',
    colors: [
      {
        name: 'Primary',
        colorName: 'lavender',
        hex: '#B497D6',
        class: 'bg-purple-300',
        hoverClass: 'hover:bg-purple-400',
        focusClass: 'ring-purple-500',
        borderClass: 'border-purple-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-purple-400',
        textPrimary: 'text-purple-500',
        textDark: 'text-purple-100',
        textOpacity: 'bg-purple-50',
        textDarkOpacity: 'bg-purple-500/30',
      },
      {
        name: 'Secondary',
        colorName: 'lilac',
        hex: '#D6AEDD',
        class: 'bg-purple-200',
        hoverClass: 'hover:bg-purple-300',
        focusClass: 'ring-purple-400/50',
        borderClass: 'border-purple-400',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-purple-300',
        textPrimary: 'text-purple-300',
        textDark: 'text-purple-50',
        textOpacity: 'bg-purple-50',
        textDarkOpacity: 'bg-purple-400/30',
      },
    ],
  },
  {
    name: 'Tropical Vibes',
    colors: [
      {
        name: 'Primary',
        colorName: 'turquoise',
        hex: '#40E0D0',
        class: 'bg-teal-400',
        hoverClass: 'hover:bg-teal-500',
        focusClass: 'ring-teal-500',
        borderClass: 'border-teal-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-teal-500',
        textPrimary: 'text-teal-400',
        textDark: 'text-teal-100',
        textOpacity: 'bg-teal-50',
        textDarkOpacity: 'bg-teal-400/30',
      },
      {
        name: 'Secondary',
        colorName: 'seafoam',
        hex: '#3B9B9A',
        class: 'bg-teal-600',
        hoverClass: 'hover:bg-teal-700',
        focusClass: 'ring-teal-600/50',
        borderClass: 'border-teal-600',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-teal-600',
        textPrimary: 'text-teal-600',
        textDark: 'text-teal-50',
        textOpacity: 'bg-teal-50',
        textDarkOpacity: 'bg-teal-600/30',
      },
    ],
  },
  {
    name: 'Peachy Sunset',
    colors: [
      {
        name: 'Primary',
        colorName: 'peach',
        hex: '#FF9A8B',
        class: 'bg-pink-400',
        hoverClass: 'hover:bg-pink-500',
        focusClass: 'ring-pink-500',
        borderClass: 'border-pink-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-pink-500',
        textPrimary: 'text-pink-400',
        textDark: 'text-pink-100',
        textOpacity: 'bg-pink-50',
        textDarkOpacity: 'bg-pink-400/30',
      },
      {
        name: 'Secondary',
        colorName: 'light-coral',
        hex: '#F2B5D4',
        class: 'bg-pink-300',
        hoverClass: 'hover:bg-pink-400',
        focusClass: 'ring-pink-400/50',
        borderClass: 'border-pink-400',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-pink-400',
        textPrimary: 'text-pink-300',
        textDark: 'text-pink-50',
        textOpacity: 'bg-pink-50',
        textDarkOpacity: 'bg-pink-300/30',
      },
    ],
  },
  {
    name: 'Autumn Charm',
    colors: [
      {
        name: 'Primary',
        colorName: 'amber',
        hex: '#FFBF00',
        class: 'bg-yellow-500',
        hoverClass: 'hover:bg-yellow-600',
        focusClass: 'ring-yellow-500',
        borderClass: 'border-yellow-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-yellow-600',
        textPrimary: 'text-yellow-500',
        textDark: 'text-yellow-100',
        textOpacity: 'bg-yellow-50',
        textDarkOpacity: 'bg-yellow-500/30',
      },
      {
        name: 'Secondary',
        colorName: 'burnt-orange',
        hex: '#CC5500',
        class: 'bg-orange-600',
        hoverClass: 'hover:bg-orange-700',
        focusClass: 'ring-orange-600/50',
        borderClass: 'border-orange-600',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-orange-700',
        textPrimary: 'text-orange-600',
        textDark: 'text-orange-50',
        textOpacity: 'bg-orange-50',
        textDarkOpacity: 'bg-orange-600/30',
      },
    ],
  },
  {
    name: 'Mint Fizz',
    colors: [
      {
        name: 'Primary',
        colorName: 'mint',
        hex: '#98FF98',
        class: 'bg-green-200',
        hoverClass: 'hover:bg-green-300',
        focusClass: 'ring-green-200',
        borderClass: 'border-green-200',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-green-300',
        textPrimary: 'text-green-200',
        textDark: 'text-green-100',
        textOpacity: 'bg-green-50',
        textDarkOpacity: 'bg-green-200/30',
      },
      {
        name: 'Secondary',
        colorName: 'light-teal',
        hex: '#4D9D9D',
        class: 'bg-teal-300',
        hoverClass: 'hover:bg-teal-400',
        focusClass: 'ring-teal-300/50',
        borderClass: 'border-teal-300',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-teal-400',
        textPrimary: 'text-teal-300',
        textDark: 'text-teal-50',
        textOpacity: 'bg-teal-50',
        textDarkOpacity: 'bg-teal-300/30',
      },
    ],
  },
  {
    name: 'Frosted Berry',
    colors: [
      {
        name: 'Primary',
        colorName: 'frosted-berry',
        hex: '#9E2A2F',
        class: 'bg-red-700',
        hoverClass: 'hover:bg-red-800',
        focusClass: 'ring-red-600',
        borderClass: 'border-red-600',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-red-800',
        textPrimary: 'text-red-700',
        textDark: 'text-red-100',
        textOpacity: 'bg-red-50',
        textDarkOpacity: 'bg-red-700/30',
      },
      {
        name: 'Secondary',
        colorName: 'berry-pink',
        hex: '#E91E63',
        class: 'bg-pink-600',
        hoverClass: 'hover:bg-pink-700',
        focusClass: 'ring-pink-600/50',
        borderClass: 'border-pink-600',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-pink-700',
        textPrimary: 'text-pink-600',
        textDark: 'text-pink-50',
        textOpacity: 'bg-pink-50',
        textDarkOpacity: 'bg-pink-600/30',
      },
    ],
  },
  {
    name: 'Moss & Stone',
    colors: [
      {
        name: 'Primary',
        colorName: 'moss-green',
        hex: '#8A9A5B',
        class: 'bg-green-600',
        hoverClass: 'hover:bg-green-700',
        focusClass: 'ring-green-500',
        borderClass: 'border-green-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-green-700',
        textPrimary: 'text-green-600',
        textDark: 'text-green-100',
        textOpacity: 'bg-green-50',
        textDarkOpacity: 'bg-green-600/30',
      },
      {
        name: 'Secondary',
        colorName: 'stone-gray',
        hex: '#9E9E9E',
        class: 'bg-gray-500',
        hoverClass: 'hover:bg-gray-600',
        focusClass: 'ring-gray-500/50',
        borderClass: 'border-gray-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-gray-600',
        textPrimary: 'text-gray-500',
        textDark: 'text-gray-50',
        textOpacity: 'bg-gray-50',
        textDarkOpacity: 'bg-gray-500/30',
      },
    ],
  },
  {
    name: 'Spicy Chili',
    colors: [
      {
        name: 'Primary',
        colorName: 'chili-red',
        hex: '#D32F2F',
        class: 'bg-red-600',
        hoverClass: 'hover:bg-red-700',
        focusClass: 'ring-red-500',
        borderClass: 'border-red-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-red-700',
        textPrimary: 'text-red-600',
        textDark: 'text-red-100',
        textOpacity: 'bg-red-50',
        textDarkOpacity: 'bg-red-600/30',
      },
      {
        name: 'Secondary',
        colorName: 'orange-peel',
        hex: '#FF5722',
        class: 'bg-orange-600',
        hoverClass: 'hover:bg-orange-700',
        focusClass: 'ring-orange-600/50',
        borderClass: 'border-orange-600',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-orange-700',
        textPrimary: 'text-orange-600',
        textDark: 'text-orange-50',
        textOpacity: 'bg-orange-50',
        textDarkOpacity: 'bg-orange-600/30',
      },
    ],
  },
  {
    name: 'Green Olive',
    colors: [
      {
        name: 'Primary',
        colorName: 'olive',
        hex: '#4CAF50',
        class: 'bg-green-500',
        hoverClass: 'hover:bg-green-600',
        focusClass: 'ring-green-500',
        borderClass: 'border-green-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-green-600',
        textPrimary: 'text-green-500',
        textDark: 'text-green-100',
        textOpacity: 'bg-green-50',
        textDarkOpacity: 'bg-green-500/30',
      },
      {
        name: 'Secondary',
        colorName: 'avocado',
        hex: '#8BC34A',
        class: 'bg-green-400',
        hoverClass: 'hover:bg-green-500',
        focusClass: 'ring-green-400/50',
        borderClass: 'border-green-400',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-green-500',
        textPrimary: 'text-green-400',
        textDark: 'text-green-50',
        textOpacity: 'bg-green-50',
        textDarkOpacity: 'bg-green-400/30',
      },
    ],
  },
  {
    name: 'Citrus Burst',
    colors: [
      {
        name: 'Primary',
        colorName: 'lemon',
        hex: '#FFEB3B',
        class: 'bg-yellow-400',
        hoverClass: 'hover:bg-yellow-500',
        focusClass: 'ring-yellow-500',
        borderClass: 'border-yellow-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-yellow-600',
        textPrimary: 'text-yellow-500',
        textDark: 'text-yellow-100',
        textOpacity: 'bg-yellow-50',
        textDarkOpacity: 'bg-yellow-500/30',
      },
      {
        name: 'Secondary',
        colorName: 'lime',
        hex: '#CDDC39',
        class: 'bg-lime-400',
        hoverClass: 'hover:bg-lime-500',
        focusClass: 'ring-lime-400/50',
        borderClass: 'border-lime-400',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-lime-500',
        textPrimary: 'text-lime-400',
        textDark: 'text-lime-50',
        textOpacity: 'bg-lime-50',
        textDarkOpacity: 'bg-lime-400/30',
      },
    ],
  },

  {
    name: 'Berry Bliss',
    colors: [
      {
        name: 'Primary',
        colorName: 'strawberry',
        hex: '#E91E63',
        class: 'bg-pink-600',
        hoverClass: 'hover:bg-pink-700',
        focusClass: 'ring-pink-500',
        borderClass: 'border-pink-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-pink-700',
        textPrimary: 'text-pink-600',
        textDark: 'text-pink-100',
        textOpacity: 'bg-pink-50',
        textDarkOpacity: 'bg-pink-600/30',
      },
      {
        name: 'Secondary',
        colorName: 'raspberry',
        hex: '#D32F2F',
        class: 'bg-red-600',
        hoverClass: 'hover:bg-red-700',
        focusClass: 'ring-red-500',
        borderClass: 'border-red-500',
        shadowClass: 'shadow-md',
        darkBgColor: 'bg-gray-900',
        textClass: 'text-neutral-500',
        textHover: 'text-red-700',
        textPrimary: 'text-red-600',
        textDark: 'text-red-100',
        textOpacity: 'bg-red-50',
        textDarkOpacity: 'bg-red-600/30',
      },
    ],
  },
];
